package com.gnoemes.shikimori.entity.app.domain

object AppExtras {
    const val ARGUMENT_ANIME_ID = "ARGUMENT_ANIME_ID"
    const val ARGUMENT_URL = "ARGUMENT_URL"
    const val ARGUMENT_TOKEN = "ARGUMENT_TOKEN"
    const val ARGUMENT_AUTH_TYPE = "ARGUMENT_AUTH_TYPE"
    const val ARGUMENT_USER_ID = "ARGUMENT_USER_ID"
    const val ARGUMENT_CHARACTER_ID = "ARGUMENT_CHARACTER_ID"
    const val ARGUMENT_FORUM_TYPE = "ARGUMENT_FORUM_TYPE"
    const val ARGUMENT_PERSON_ID = "ARGUMENT_PERSON_ID"
    const val ARGUMENT_SEARCH_DATA = "ARGUMENT_SEARCH_DATA"
    const val ARGUMENT_MANGA_DATA = "ARGUMENT_MANGA_DATA"
    const val ARGUMENT_TOPIC_ID = "ARGUMENT_TOPIC_ID"
    const val ARGUMENT_EPISODES_DATA = "ARGUMENT_EPISODES_DATA"
    const val ARGUMENT_PLAYER_DATA = "ARGUMENT_PLAYER_DATA"
    const val ARGUMENT_RATE_DATA = "ARGUMENT_RATE_DATA"
}